### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Badafest** [samrachana/Samrachana-Araniko#1]
Check the box only after the task has been completed. @aarsonmars 
-  [ ] Fix object tree
-  [ ] CONTRIBUTING.md
-  [ ] pre-release installer for windows
-  [ ] pre-release distribution for building [macOS, Linux and for devs]
- [ ] make samrachana.github.io site
