### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Badafest** [samrachana/Samrachana-Araniko#2]
- [ ] prepare docs
- [ ] perform feature testing [feature list from docs[
- [ ] prepare distribution for building from source
- [ ] prepare installers for alpha version
- [ ] invite sample users for alpha testing
